### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker_sync#4]
Hi,

Thanks for working on this project.

I tried to configure my own docker project ith docker_sync and also tried the boiler plate but each ends with the error:

          ok  Starting unison
    /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_strategy/unison.rb:38:in `sync': undefined method `join' for nil:NilClass (NoMethodError)
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_strategy/unison.rb:93:in `start_container'
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_strategy/unison.rb:32:in `run'
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_process.rb:64:in `run'
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_manager.rb:103:in `block in run'
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_manager.rb:102:in `each'
	from /Users/mickaelperrin/tmp/docker_sync/lib/docker_sync/sync_manager.rb:102:in `run'
	from /Users/mickaelperrin/tmp/docker_sync/tasks/sync.thor:32:in `start'
	from /Users/mickaelperrin/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/mickaelperrin/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mickaelperrin/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mickaelperrin/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ../../docker_sync/bin/docker-sync:11:in `<main>'

It looks like the `args` are not properly parsed. 

Am I missing something ?

Regards,

**Comment by EugenMayer** [comment]
thanks for fixing the bug yourself - pitty that slipped through my test - i do not have any unit tests yet ( not easy to write it for this tool though )
